function materials = listAttenuatorMaterials(materialType)
%LISTATTENUATORMATERIALS Return material metadata suitable for a UI.
%
% materials = listAttenuatorMaterials() returns all elements and compounds.
% materials = listAttenuatorMaterials("element") returns only elements.
% materials = listAttenuatorMaterials("compound") returns only compounds.

arguments
    materialType (1, 1) string {mustBeMember(materialType, ...
        ["all", "element", "compound"])} = "all"
end

catalog = loadAttenuatorCatalog();
elementCount = catalog.metadata.elementCount;
compoundCount = catalog.metadata.compoundCount;

elements = table( ...
    repmat("element", elementCount, 1), ...
    (1:elementCount)', ...
    string(catalog.elements.symbols(:)), ...
    string(catalog.elements.displayNames(:)), ...
    catalog.elements.atomicNumbers(:), ...
    catalog.elements.density_g_cm3(:), ...
    'VariableNames', ...
    {'Type', 'Index', 'Key', 'DisplayName', 'AtomicNumber', ...
     'Density_g_cm3'});

compounds = table( ...
    repmat("compound", compoundCount, 1), ...
    (1:compoundCount)', ...
    string(catalog.compounds.names(:)), ...
    string(catalog.compounds.names(:)), ...
    nan(compoundCount, 1), ...
    catalog.compounds.density_g_cm3(:), ...
    'VariableNames', ...
    {'Type', 'Index', 'Key', 'DisplayName', 'AtomicNumber', ...
     'Density_g_cm3'});

switch materialType
    case "element"
        materials = elements;
    case "compound"
        materials = compounds;
    otherwise
        materials = [elements; compounds];
end
end
