function result = runSpectrumAnalysis(kV, materialIdentifier, ...
        thicknessMm, options)
%RUNSPECTRUMANALYSIS Run attenuation, detector response, and bin separation.

arguments
    kV (1, 1) double {mustBeMember(kV, [70 90 120 140])}
    materialIdentifier
    thicknessMm (1, 1) double {mustBeNonnegative, mustBeFinite}
    options.MaterialType (1, 1) string {mustBeMember(options.MaterialType, ...
        ["auto", "element", "compound"])} = "auto"
    options.LowThresholdKeV (1, 1) double {mustBeFinite} = 20
    options.SplitThresholdKeV (1, 1) double = nan
    options.HighThresholdKeV (1, 1) double {mustBeFinite} = 150
    options.IncidentFile (1, 1) string = defaultIncidentFile()
    options.ResponseFile (1, 1) string = defaultResponseFile()
end

utilsDir = fileparts(mfilename("fullpath"));
interfaceDir = fileparts(utilsDir);
attenuatorDir = fullfile(interfaceDir, "attenuator");
if isempty(which("getAttenuatorMaterial"))
    addpath(attenuatorDir);
end

[incidentSpectrum, incidentEnergyKeV, incidentMetadata] = ...
    loadIncidentSpectrum(kV, options.IncidentFile);
[responseMatrix, responseInputEnergyKeV, detectedEnergyKeV] = ...
    loadAlphaEnergyResponse(options.ResponseFile);
responseColormap = loadAlphaEnergyColormap();

if ~isequal(incidentEnergyKeV, responseInputEnergyKeV)
    error("spectrum:EnergyGridMismatch", ...
        "Incident spectrum and energy-response input grids must match.");
end

material = getAttenuatorMaterial( ...
    materialIdentifier, options.MaterialType);
if ~isequal(material.energy_keV(:), incidentEnergyKeV)
    error("spectrum:AttenuatorEnergyGridMismatch", ...
        "Attenuator and incident-spectrum energy grids must match.");
end

[postObjectSpectrum, transmission] = calculatePostObjectSpectrum( ...
    incidentSpectrum, material.linearAttenuation_mm_inv(:), thicknessMm);
outputSpectrum = calculateOutputSpectrum( ...
    postObjectSpectrum, responseMatrix);
outputSpectrum(detectedEnergyKeV < 20) = 0;

splitThresholdKeV = options.SplitThresholdKeV;
if isnan(splitThresholdKeV)
    splitThresholdKeV = defaultSplitThreshold(kV);
elseif ~isfinite(splitThresholdKeV)
    error("spectrum:InvalidSplitThreshold", ...
        "The split threshold must be finite.");
end
thresholdsKeV = [
    options.LowThresholdKeV
    splitThresholdKeV
    options.HighThresholdKeV
]';
bins = separateSpectrumBins( ...
    postObjectSpectrum, responseMatrix, incidentEnergyKeV, ...
    detectedEnergyKeV, thresholdsKeV);

incidentCounts = sum(incidentSpectrum);
postObjectCounts = sum(postObjectSpectrum);
if incidentCounts > 0
    transmittedFraction = postObjectCounts / incidentCounts;
else
    transmittedFraction = nan;
end

result = struct( ...
    "kV", kV, ...
    "material", material, ...
    "thickness_mm", thicknessMm, ...
    "thresholds_keV", thresholdsKeV, ...
    "inputEnergy_keV", incidentEnergyKeV, ...
    "detectedEnergy_keV", detectedEnergyKeV, ...
    "responseMatrix", responseMatrix, ...
    "responseColormap", responseColormap, ...
    "incidentSpectrum", incidentSpectrum, ...
    "transmission", transmission, ...
    "postObjectSpectrum", postObjectSpectrum, ...
    "outputSpectrum", outputSpectrum, ...
    "lowSpectrum", bins.lowSpectrum, ...
    "highSpectrum", bins.highSpectrum, ...
    "lowInputContributionSpectrum", ...
        bins.lowInputContributionSpectrum, ...
    "highInputContributionSpectrum", ...
        bins.highInputContributionSpectrum, ...
    "outputLowSpectrum", bins.outputLowSpectrum, ...
    "outputHighSpectrum", bins.outputHighSpectrum, ...
    "lowCounts", bins.lowCounts, ...
    "highCounts", bins.highCounts, ...
    "trueLowCounts", bins.trueLowCounts, ...
    "misclassifiedHighCounts", bins.misclassifiedHighCounts, ...
    "misclassifiedLowCounts", bins.misclassifiedLowCounts, ...
    "trueHighCounts", bins.trueHighCounts, ...
    "incidentCounts", incidentCounts, ...
    "postObjectCounts", postObjectCounts, ...
    "outputCounts", sum(outputSpectrum), ...
    "transmittedFraction", transmittedFraction, ...
    "binBoundaryConvention", bins.boundaryConvention, ...
    "incidentMetadata", incidentMetadata);
end

function splitThresholdKeV = defaultSplitThreshold(kV)
switch kV
    case 70
        splitThresholdKeV = 53;
    case 90
        splitThresholdKeV = 64;
    otherwise
        splitThresholdKeV = 68;
end
end

function incidentFile = defaultIncidentFile()
utilsDir = fileparts(mfilename("fullpath"));
interfaceDir = fileparts(utilsDir);
incidentFile = fullfile( ...
    interfaceDir, "incident_spectra", "incident_spectrum.mat");
end

function responseFile = defaultResponseFile()
utilsDir = fileparts(mfilename("fullpath"));
interfaceDir = fileparts(utilsDir);
responseFile = fullfile( ...
    interfaceDir, "energy_response", "AlphaEnergyResponse.txt");
end
