function bins = separateSpectrumBins(postObjectSpectrum, responseMatrix, ...
        inputEnergyKeV, detectedEnergyKeV, thresholdsKeV)
%SEPARATESPECTRUMBINS Calculate input-energy contributions to detector bins.
%
% thresholdsKeV = [lower split upper]. The low bin is
% lower <= E_detected < split and the high bin is
% split <= E_detected <= upper. Assigning the split threshold only to the
% high bin prevents double-counting.

arguments
    postObjectSpectrum (:, 1) double {mustBeNonnegative, mustBeFinite}
    responseMatrix (:, :) double {mustBeNonnegative, mustBeFinite}
    inputEnergyKeV (:, 1) double {mustBeFinite}
    detectedEnergyKeV (:, 1) double {mustBeFinite}
    thresholdsKeV (1, 3) double {mustBeFinite}
end

if size(responseMatrix, 1) ~= numel(inputEnergyKeV) || ...
        size(responseMatrix, 2) ~= numel(detectedEnergyKeV) || ...
        numel(postObjectSpectrum) ~= numel(inputEnergyKeV)
    error("spectrum:BinSizeMismatch", ...
        "Spectrum, response matrix, and energy grids have inconsistent sizes.");
end

lowerThreshold = thresholdsKeV(1);
splitThreshold = thresholdsKeV(2);
upperThreshold = thresholdsKeV(3);
if ~(lowerThreshold < splitThreshold && splitThreshold <= upperThreshold)
    error("spectrum:InvalidThresholds", ...
        "Thresholds must satisfy lower < split <= upper.");
end
if lowerThreshold < min(detectedEnergyKeV) || ...
        upperThreshold > max(detectedEnergyKeV)
    error("spectrum:ThresholdsOutsideGrid", ...
        "Thresholds must lie within the detected-energy grid.");
end

lowMask = detectedEnergyKeV >= lowerThreshold & ...
    detectedEnergyKeV < splitThreshold;
highMask = detectedEnergyKeV >= splitThreshold & ...
    detectedEnergyKeV <= upperThreshold;

lowDetectionWeight = sum(responseMatrix(:, lowMask), 2);
highDetectionWeight = sum(responseMatrix(:, highMask), 2);
lowSpectrum = postObjectSpectrum .* lowDetectionWeight;
highSpectrum = postObjectSpectrum .* highDetectionWeight;

trueLowInputMask = inputEnergyKeV < splitThreshold;
trueHighInputMask = inputEnergyKeV >= splitThreshold;
trueLowCounts = sum(lowSpectrum(trueLowInputMask));
misclassifiedHighCounts = sum(lowSpectrum(trueHighInputMask));
misclassifiedLowCounts = sum(highSpectrum(trueLowInputMask));
trueHighCounts = sum(highSpectrum(trueHighInputMask));

outputSpectrum = responseMatrix' * postObjectSpectrum;
outputLowSpectrum = zeros(size(outputSpectrum));
outputHighSpectrum = zeros(size(outputSpectrum));
outputLowSpectrum(lowMask) = outputSpectrum(lowMask);
outputHighSpectrum(highMask) = outputSpectrum(highMask);

bins = struct( ...
    "thresholds_keV", thresholdsKeV, ...
    "boundaryConvention", "[lower, split) and [split, upper]", ...
    "inputEnergy_keV", inputEnergyKeV, ...
    "detectedEnergy_keV", detectedEnergyKeV, ...
    "lowMask", lowMask, ...
    "highMask", highMask, ...
    "lowDetectionWeight", lowDetectionWeight, ...
    "highDetectionWeight", highDetectionWeight, ...
    "lowSpectrum", lowSpectrum, ...
    "highSpectrum", highSpectrum, ...
    "trueLowInputMask", trueLowInputMask, ...
    "trueHighInputMask", trueHighInputMask, ...
    "lowInputContributionSpectrum", lowSpectrum, ...
    "highInputContributionSpectrum", highSpectrum, ...
    "outputLowSpectrum", outputLowSpectrum, ...
    "outputHighSpectrum", outputHighSpectrum, ...
    "lowCounts", sum(lowSpectrum), ...
    "highCounts", sum(highSpectrum), ...
    "trueLowCounts", trueLowCounts, ...
    "misclassifiedHighCounts", misclassifiedHighCounts, ...
    "misclassifiedLowCounts", misclassifiedLowCounts, ...
    "trueHighCounts", trueHighCounts);
end
